spring:
  datasource:
    url: jdbc:mysql://8.137.158.83:6001/union_lotto?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
    username: tiankong
    password: zh34864486
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
  redis:
    host: 8.137.158.83
    # 端口，默认为6379
    port: 7001
    # 数据库索引
    database: 0
    # 密码
    password: zh34864486
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      file-size-threshold: 11MB
      max-request-size: 10MB
      resolve-lazily: false
