spring:
  datasource:
    dynamic:
      primary: master # 配置默认数据库
      strict: false
      datasource:
        master:
          # tcpRcvBuf/tcpSndBuf 缓冲区参数 rewriteBatchedStatements batchUpdate参数
          url: jdbc:mysql://xy.tiankong44.vip:6001/tk_tabs?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
          username: root
          password: zh34864486
#        slave:
#          # tcpRcvBuf/tcpSndBuf 缓冲区参数 rewriteBatchedStatements batchUpdate参数
#          url: jdbc:mysql://xy.tiankong44.vip:6002/tk_tabs?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
#          username: root
#          password: zh34864486
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
  driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #    cluster:
    #      nodes: 127.0.0.1:6379
    password: root
    host: localhost
    port: 6379
  config:
    activate:
      on-profile: out
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      location: E:\upload
      max-request-size: 50MB
      resolve-lazily: false
images-url-prefix: http://xy.tiankong44.vip:9200/images/